// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $api_blocks from "./routes/api/blocks.ts";
import * as $api_getblockchaininfo from "./routes/api/getblockchaininfo.ts";
import * as $api_getblockcount from "./routes/api/getblockcount.ts";
import * as $api_getblockhash_height_ from "./routes/api/getblockhash/[height].ts";
import * as $api_invoice from "./routes/api/invoice.ts";
import * as $api_invoice_callback from "./routes/api/invoice/callback.ts";
import * as $api_period_period_ from "./routes/api/period/[period].ts";
import * as $api_periods from "./routes/api/periods.ts";
import * as $index from "./routes/index.tsx";
import * as $index_txt from "./routes/index.txt.tsx";
import * as $miner_miner_ from "./routes/miner/[miner].tsx";
import * as $miners from "./routes/miners.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $stats from "./routes/stats.tsx";
import * as $BlockGrid from "./islands/BlockGrid.tsx";
import * as $Donation from "./islands/Donation.tsx";
import * as $ForkStatus from "./islands/ForkStatus.tsx";
import * as $MinersTable from "./islands/MinersTable.tsx";
import * as $ProgressBar from "./islands/ProgressBar.tsx";
import * as $SettingsForm from "./islands/SettingsForm.tsx";
import * as $SiteMenu from "./islands/SiteMenu.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/api/blocks.ts": $api_blocks,
    "./routes/api/getblockchaininfo.ts": $api_getblockchaininfo,
    "./routes/api/getblockcount.ts": $api_getblockcount,
    "./routes/api/getblockhash/[height].ts": $api_getblockhash_height_,
    "./routes/api/invoice.ts": $api_invoice,
    "./routes/api/invoice/callback.ts": $api_invoice_callback,
    "./routes/api/period/[period].ts": $api_period_period_,
    "./routes/api/periods.ts": $api_periods,
    "./routes/index.tsx": $index,
    "./routes/index.txt.tsx": $index_txt,
    "./routes/miner/[miner].tsx": $miner_miner_,
    "./routes/miners.tsx": $miners,
    "./routes/settings.tsx": $settings,
    "./routes/stats.tsx": $stats,
  },
  islands: {
    "./islands/BlockGrid.tsx": $BlockGrid,
    "./islands/Donation.tsx": $Donation,
    "./islands/ForkStatus.tsx": $ForkStatus,
    "./islands/MinersTable.tsx": $MinersTable,
    "./islands/ProgressBar.tsx": $ProgressBar,
    "./islands/SettingsForm.tsx": $SettingsForm,
    "./islands/SiteMenu.tsx": $SiteMenu,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
